### ISSUE TITLE
🐛 [Bug]: 能通过调用api的方式来实现添加提及人嘛，比如我点击了某个按钮添加@提及人

### ISSUE THREAD

**Issue by zhouyonghuan** [opentiny/fluent-editor#110]
### Version

1

### Link to minimal reproduction

1

### Step to reproduce

1

### What is expected

1

### What is actually happening

1

### What is your project name

1

### Any additional comments (optional)

1

**Comment by Linkodt** [comment]
这个是不是可以自己写个函数，调用之后往内容里面加@符号就行了？

**Comment by zzxming** [comment]
可以确定好你想要插入的位置以及正确的delta结构之后调用 [`insertEmbed`](https://quilljs.com/docs/api#insertembed)

```js
editor.insertEmbed(0, 'mention', {
  char: '@',
  text: 'Jack 杰克',
  name: 'Jack',
})
```
