### ISSUE TITLE
✨ [Feature]: 工具栏表格支持选择多行多列表格

### ISSUE THREAD

**Issue by kagol** [opentiny/fluent-editor#135]
### What problem does this feature solve

目前表格工具栏按钮只支持插入3*3的表格，希望支持以下这种选择多行多列的效果（类似：语雀）

![image](https://github.com/user-attachments/assets/0f4591c6-f62b-4a06-9801-93ccd829a727)

### What does the proposed API look like

如上

### What is your project name

Wiki

**Comment by jany55555** [comment]
请问最多支持多少*多少呢

**Comment by SunshineWithMoon** [comment]
最多10✖️10

**Comment by kagol** [comment]
Finished by @jany55555 in #151
