### ISSUE TITLE
✨ [Feature]: 新增自定义工具

### ISSUE THREAD

**Issue by qq707631575** [opentiny/fluent-editor#149]
### What problem does this feature solve

方便使用者添加自己开发的工具

### What does the proposed API look like

建议提供文档和接入指引

### What is your project name

yejy

**Comment by kagol** [comment]
参考文档：[https://opentiny.github.io/fluent-editor/docs/add-toolbar-item](https://opentiny.github.io/fluent-editor/docs/add-toolbar-item)
