### ISSUE TITLE
🐛 [Bug]: 开启附件功能后没有回调方法

### ISSUE THREAD

**Issue by qq707631575** [opentiny/fluent-editor#156]
### Version

latest

### Link to minimal reproduction

本地

### Step to reproduce

上传附件后，点击下载按钮，打开新页签，没有进行下载

### What is your project name

本地

**Comment by kagol** [comment]
Fixed by @qwangry in #160

**Comment by qq707631575** [comment]
附件上传没有接收id导致删除无法回调
