### ISSUE TITLE
🐛 [Bug]: video触发Enter Video按键无效

### ISSUE THREAD

**Issue by aimilu** [opentiny/fluent-editor#17]
### Version

3.18.3

### Link to minimal reproduction

video触发Enter Video按键无效。

### Step to reproduce

toolbar添加video，触发工具栏video控件，弹出添加链接弹窗，输入链接后，按Enter键无法回显到富文本编辑器。

### What is expected

输入链接后，按Enter键或点击保存按钮，将video填充到富文本内容。

### What is actually happening

无法将video回显到文本编辑器

### What is your project name

ERP

**Comment by kagol** [comment]
@aimilu Fixed by @zzxming on #34
