### ISSUE TITLE
🐛 [Bug]: v-model用html模式（设置data-type为false）img 和video标签的src属性丢失

### ISSUE THREAD

**Issue by wangiel** [opentiny/fluent-editor#31]
### Version

3.18.0

### Link to minimal reproduction

`<a-form-item label="内容" field="content">
          <TinyFluentEditor v-model="form.content" :data-type="false" :data-upgrade="false" :options="options"></TinyFluentEditor>
         </a-form-item>`

### Step to reproduce

加载其它富文本编辑器的内容，发现img video标签的src属性丢失

### What is your project name

小记者系统

**Comment by kagol** [comment]
应该是 Vue 版本的 Fluent Editor 组件的问题，已记录在：[tiny-vue#2008](https://github.com/opentiny/tiny-vue/issues/2008)
