### ISSUE TITLE
🐛 [Bug]: 为什么quill原本的粘贴图片的功能没有了呢？

### ISSUE THREAD

**Issue by zttAsoiaf** [opentiny/fluent-editor#41]
### Version

最新版

### Link to minimal reproduction

https://github.com/opentiny/fluent-editor

### Step to reproduce

粘贴图片到富文本框

### What is expected

可以显示图片

### What is actually happening

无法显示图片

### What is your project name

无

**Comment by Janson1012** [comment]
有最小可复现demo吗

**Comment by zttAsoiaf** [comment]
Quill的功能
https://codepen.io/attoae/pen/WNBGjZp   这是Quill的demo
https://quilljs.com/docs/quickstart  这个也可以，点击run code 就可以了。
直接截图粘贴就可以了

这个是fluent-editor，无法截图粘贴
https://opentiny.github.io/fluent-editor/docs/basic-usage

**Comment by Janson1012** [comment]
> Quill的功能 https://codepen.io/attoae/pen/WNBGjZp 这是Quill的demo https://quilljs.com/docs/quickstart 这个也可以，点击run code 就可以了。 直接截图粘贴就可以了
> 
> 这个是fluent-editor，无法截图粘贴 https://opentiny.github.io/fluent-editor/docs/basic-usage

需要在初始化editor配置的时候把uploadOption里的imageUploadToServer改为true就可以使用了，不好意思，文档说明不够清晰
@Kagol

**Comment by zttAsoiaf** [comment]
![image](https://github.com/user-attachments/assets/5bc5d8c4-6f66-47ce-b8ae-1c7ebbecff12)
赞赞赞，果然可以了。
解决问题速度杠杠的。
