### ISSUE TITLE
✨ [Feature]: 请问一下这个组件是否支持全屏

### ISSUE THREAD

**Issue by zttAsoiaf** [opentiny/fluent-editor#44]
### What problem does this feature solve

是否有全屏专注模式，支持放大和缩小？

### What does the proposed API look like

![image](https://github.com/user-attachments/assets/fd57d281-cc26-4136-b1f1-e5121655bc7d)
类似这样

### What is your project name

*

**Comment by Janson1012** [comment]
第一个开启全屏按钮，第二个是配置全屏按钮事件，全屏功能写在这个事件里面，由使用者做UI层适配
![image](https://github.com/user-attachments/assets/ca6d9caf-7954-4b81-a814-cb3c32b0b49b)
![image](https://github.com/user-attachments/assets/520f48d4-a5b8-464a-a460-c969ac05eae3)

**Comment by kagol** [comment]
全屏是很实用的功能，后续可以集成到 Fluent Edtior 中
