### ISSUE TITLE
✨ [Feature]: 是否支持指定 toolbar 容器

### ISSUE THREAD

**Issue by ihwf** [opentiny/fluent-editor#46]
### What problem does this feature solve

支持指定 toolbar 容器, 实现内容区与工具栏分离

### What does the proposed API look like

```
new FluentEditor('#editor', {
    theme: 'snow',
    modules: {
        toolbar: {
            container: "#toolbar",
            controls: [
                ['undo', 'redo', 'clean'],
            ]
        },
    },
})
```

### What is your project name

editor

**Comment by zzxming** [comment]
`toolbar.container` 是支持的，配置方式与 Quill 官方 [toolbar 模块](https://quilljs.com/docs/modules/toolbar#container)一致，不需要 `toolbar.controls`

**Comment by ihwf** [comment]
貌似 Quill官方使用了 `toolbar. container` 就不能同时用 format names 数组配置工具栏 😂, 只能使用 `toolbar. container` 或者使用format names 数组配置, 如果指定 `toolbar. container` , 就只能在 dom 中写一堆 html, 当然, 可以从 Quill 的 [toolbar.ts](https://github.com/slab/quill/blob/main/packages/quill/src/modules/toolbar.ts#L201) 中导入 `addControls`, 用`addControls`生成需要的工具栏,   Quill 源码中 [toolbar.ts](https://github.com/slab/quill/blob/main/packages/quill/src/modules/toolbar.ts#L201) 是有把 `addControls` 导出的, 但是 `fluent-editor` 中没有把 `addControls` 导出?

**Comment by zzxming** [comment]
理解意思了，目前 `fluent-editor` 没有导出 `Quill` 中的辅助函数，如果要使用的话要额外安装 `Quill` 本体。 @kagol 是否需要实现此功能

**Comment by ihwf** [comment]
对, 是这个意思,  或者是否可以添加支持 `fluent-editor` 实例化的时候加个 `toolbar.controls` 参数,  内部调用 `addControls` 实现 `toolbar. container` 与 format names 数组同时使用?

**Comment by kagol** [comment]
> 理解意思了，目前 `fluent-editor` 没有导出 `Quill` 中的辅助函数，如果要使用的话要额外安装 `Quill` 本体。 @kagol 是否需要实现此功能

建议导出 Quill 相关内容，理论上 Quill 有的，都可以通过 Fluent Editor 导出。

**Comment by zzxming** [comment]
3.19.1 版本已实现 `fluent-editor` 分离，需要额外安装 `quill` 作为依赖，可从 `quill` 中导出辅助函数使用
