### ISSUE TITLE
🐛 [Bug]: 文档缺少上传的相关说明

### ISSUE THREAD

**Issue by ihwf** [opentiny/fluent-editor#47]
### Version

latest

### Link to minimal reproduction

[官网图片上传](https://opentiny.github.io/fluent-editor/docs/image-upload)

### Step to reproduce

文档中缺少关于上传的相关配置说明, 比如如何在选择文件后执行回调, 如何将图片/文件上传到服务器?

### What is expected

完善上传配置说明

### What is your project name

editor

**Comment by kagol** [comment]
文档这块我们正在完善中

**Comment by kagol** [comment]
@ihwf 已完善图片上传服务器的demo文档。
[https://opentiny.github.io/fluent-editor/docs/image-upload#上传到服务器](https://opentiny.github.io/fluent-editor/docs/image-upload#%E4%B8%8A%E4%BC%A0%E5%88%B0%E6%9C%8D%E5%8A%A1%E5%99%A8)
