### ISSUE TITLE
✨ [Feature]: 请问一下fluent-editor是否支持国际化

### ISSUE THREAD

**Issue by zttAsoiaf** [opentiny/fluent-editor#49]
### What problem does this feature solve

![image](https://github.com/user-attachments/assets/59fa4318-4910-46bc-9b20-f7079355b7e4)
better table 右键如何配置国际化

### What does the proposed API look like

支持国际化

### What is your project name

*

**Comment by kagol** [comment]
@zttAsoiaf 暂不支持国际化，不过这个表格右菜单的内容是可以自己配置的。

**Comment by zttAsoiaf** [comment]
这个表格内容怎么配置，有没有相关文档？

**Comment by kagol** [comment]
> 这个表格内容怎么配置，有没有相关文档？

有的，参考下这个文档：
[https://opentiny.github.io/fluent-editor/docs/table](https://opentiny.github.io/fluent-editor/docs/table)
