### ISSUE TITLE
🐛 [Bug]: 获取 HTML demo 报错：Error: Syntax module requires highlight.js

### ISSUE THREAD

**Issue by kagol** [opentiny/fluent-editor#58]
### Version

latest

### Link to minimal reproduction

复现步骤：

- 打开 https://opentiny.github.io/fluent-editor/
- 点击开始按钮
- 点击基本用法 demo
- 点击获取HTML 的demo
- F12控制台报错，并且富文本中的内容未显示

![image](https://github.com/user-attachments/assets/d2b2fdf8-9633-4e81-9f23-c3a3422b06bc)

### Step to reproduce

同上

### What is your project name

Demo

**Comment by zzxming** [comment]
缓存问题...，我勾选 `Disable cache` 重新加载后没有出现 `highlight.js` 错误，之后重新构建生成新id应该就好了。另外 `formula` 不是模块，只需要在 `toolbar` 中配置了就可以用了
