### ISSUE TITLE
🐛 [Bug]: 复制 Word 文档中的内容，部分格式丢失

### ISSUE THREAD

**Issue by kagol** [opentiny/fluent-editor#61]
主要有以下格式丢失：
- 字体
- 字号
- 行距
- 缩进

**Comment by ihwf** [comment]
还会丢失 
- 编号列表
同时存在的问题是, 开启了 `uploadOption.imageUploadToServer` 再粘贴 word 中复制的文字内容时, 文字都变成了图片, 关闭  `uploadOption.imageUploadToServer` 时, 就无法粘贴图片
