### ISSUE TITLE
🐛 [Bug]: CTRL+Z 回退有问题

### ISSUE THREAD

**Issue by zttAsoiaf** [opentiny/fluent-editor#69]
### Version

3.19.1

### Link to minimal reproduction

*

### Step to reproduce

随意输入一些文字
a
b
c
d

这时如果按 CTRL + Z，则会删除c，而不是删除d

### What is expected

![image](https://github.com/user-attachments/assets/c1fd867d-4e59-4858-8a2c-4f8a251e763e)

### What is actually happening

![image](https://github.com/user-attachments/assets/f42a79fe-31f6-4b57-9413-8a4934972006)

### What is your project name

*

**Comment by zttAsoiaf** [comment]
2.   先输入 abc，然后选中 abc，再输入 efg
此时按CTRL + Z，显示fg，再次按，无反应。
3.  输入 abc，直接按 CTRL + Z，无反应。

**Comment by kagol** [comment]
@zttAsoiaf 按照你的操作并不能复现，可以尝试录个视频。

撤销操作基于 Quill 的 History 模块，默认每隔 1s 记录一次操作历史。

**Comment by zttAsoiaf** [comment]
![screenshots](https://github.com/user-attachments/assets/fef4f7d0-202d-466d-bd0a-03307c21e971)
看这个

**Comment by zttAsoiaf** [comment]
我又测试了一下 3.9.2 版本，确实不能重现。可以暂时关闭

**Comment by kagol** [comment]
> 我又测试了一下 3.9.2 版本，确实不能重现。可以暂时关闭

好的，后续有问题再提🤝
