### ISSUE TITLE
✨ [Feature]:  大佬有办法实现一个h1-h2-h3标题文字只是选中部分样式变化而不是一整行变化吗。

### ISSUE THREAD

**Issue by hongdundada** [opentiny/fluent-editor#71]
### What problem does this feature solve

大佬有办法实现一个h1-h2-h3标题文字只是选中部分样式变化而不是一整行变化吗。

### What does the proposed API look like

大佬有办法实现一个h1-h2-h3标题文字只是选中部分样式变化而不是一整行变化吗。

### What is your project name

 大佬有办法实现一个h1-h2-h3标题文字只是选中部分样式变化而不是一整行变化吗。

**Comment by zttAsoiaf** [comment]
markdown 没这种用法吧。你需要的是富文本

**Comment by zttAsoiaf** [comment]
你这个应该是更改字体大小的功能，跟标题无关。参考下面这个试一下行不行
https://blog.csdn.net/n1234567896/article/details/119795050

**Comment by hongdundada** [comment]
![1](https://github.com/user-attachments/assets/086484d5-ede6-47c3-ba0b-db30a382216a)
就是想要实现 比如局部选中文字 仅仅这部分文字实现h1标题 或者h2标题 或者h3标题文字 而不是一整行都是

**Comment by hongdundada** [comment]
> 你这个应该是更改字体大小的功能，跟标题无关。参考下面这个试一下行不行 https://blog.csdn.net/n1234567896/article/details/119795050

**Comment by zzxming** [comment]
h1-h6是块级元素，你可以使用加粗和改变字体大小实现

**Comment by kagol** [comment]
@hongdundada 参考下 @zttAsoiaf @zzxming 的建议即可。
