### ISSUE TITLE
✨ [Feature]: 为什么npm上面下载下来 就没有ts文件了-我看github上面代码里面是ts文件

### ISSUE THREAD

**Issue by hongdundada** [opentiny/fluent-editor#73]
### What problem does this feature solve

![image](https://github.com/user-attachments/assets/353119e8-2b3c-41bb-aa79-45927d2bacd2)

### What does the proposed API look like

![image](https://github.com/user-attachments/assets/2ddbce8b-923e-4510-8243-dd440da057fd)

### What is your project name

为什么npm上面下载下来 就没有ts文件了-我看github上面代码里面是ts文件

**Comment by kagol** [comment]
@hongdundada ts确实有问题，我们来修复下哈

**Comment by WindRunnerMax** [comment]
简单试了一下，发现如果用 vite 配合 rollup 的 typescript plugin 会有一些问题，分别打包 es 和 cjs 需要分别调度 rollup 打包才行，或许直接用 tsc 打包 ts 文件更方便一些？

**Comment by kagol** [comment]
> 简单试了一下，发现如果用 vite 配合 rollup 的 typescript plugin 会有一些问题，分别打包 es 和 cjs 需要分别调度 rollup 打包才行，或许直接用 tsc 打包 ts 文件更方便一些？

@WindRunnerMax @hongdundada 我试了下，通过 vite-plugin-dst 插件打包是可以正确生成 ts 类型声明文件的，已发布 alpha 版本：`@opentiny/fluent-editor@3.20.4-alpha.0`

**Comment by kagol** [comment]
@hongdundada 已发布正式版本 v3.21.0，导出了 TypeScript 类型声明。
