### ISSUE TITLE
✨ [Feature]: 工具栏图标建议 hover 上去通过 tooltip 提示图标按钮的用途

### ISSUE THREAD

**Issue by kagol** [opentiny/fluent-editor#98]
### What problem does this feature solve

效果如下：
![image](https://github.com/user-attachments/assets/d3f9178c-cb7a-4c05-9b94-17087846cc87)

### What does the proposed API look like

同上

### What is your project name

Wiki

**Comment by inherents** [comment]
同上

**Comment by Linkodt** [comment]
引用外部tooltip组件(如tiny-vue)实现，还是纯用css+html实现呢？
